

#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;DatabaseName=bonatto2;prepareSQL=3;cachemetadata=true
#spring.datasource.username=sa
#spring.datasource.password=chica


spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.show-sql=false
